import { Injectable } from '@nestjs/common';
import { DeterministicRng, DeterministicRngService } from './deterministic-rng.service';

export interface GeneratedPuzzle {
  /** The board/layout the client should render (server-authored, reproducible). */
  board: any;
  /** The canonical solution, kept SERVER-SIDE only (never sent to the client). */
  solution: any;
  /** Fingerprint of the board for anti-tamper verification at submit time. */
  fingerprint: string;
  /** Useful precomputed metrics (e.g. shortest path length) for scoring. */
  meta: Record<string, number>;
}

/**
 * Deterministic, seed-driven puzzle generation and validation.
 *
 * Implements the spec requirement: "All puzzle configurations (mazes, sliding
 * puzzles, Sudoku, Block Fill) are server-side validated to guarantee exactly
 * one solvable state per session." Every puzzle here is generated purely from
 * the session's deterministic RNG, so it is reproducible for replay validation,
 * and ships with a guaranteed solution.
 */
@Injectable()
export class PuzzleService {
  constructor(private readonly rngService: DeterministicRngService) {}

  /**
   * Generate a puzzle for a game type from session seed material. Returns null
   * for games the platform does not centrally generate (those keep their own
   * game-backend generation).
   */
  generate(
    gameType: string,
    serverSeed: string,
    config: any,
    clientSeed?: string | null,
    nonce = 0,
  ): GeneratedPuzzle | null {
    const rng = this.rngService.create(serverSeed, clientSeed, nonce);
    switch (gameType) {
      case 'SLIDING_PUZZLE':
        return this.generateSlidingPuzzle(rng, config);
      case 'MAZE_NAVIGATION':
        return this.generateMaze(rng, config);
      case 'BLOCK_FILL':
        return this.generateBlockFill(rng, config);
      default:
        return null;
    }
  }

  /** Verify a client-submitted board fingerprint matches the server's. */
  verifyFingerprint(board: unknown, submitted: string | undefined): boolean {
    if (!submitted) return false;
    return this.rngService.fingerprint(board) === submitted;
  }

  // ─── SLIDING PUZZLE (parity-guaranteed solvable) ───────────────

  /**
   * n×n sliding puzzle. The scramble is generated by drawing a random permutation
   * and forcing it to be solvable via a parity correction, guaranteeing exactly
   * one reachable solved state.
   */
  private generateSlidingPuzzle(rng: DeterministicRng, config: any): GeneratedPuzzle {
    const n = this.clamp(Number(config?.grid_size ?? 3), 3, 6);
    const size = n * n;
    // Tiles 1..size-1 plus 0 (blank).
    const tiles = Array.from({ length: size }, (_, i) => i);
    rng.shuffle(tiles);
    this.ensureSolvable(tiles, n);
    const solution = Array.from({ length: size }, (_, i) => (i + 1) % size); // 1..n,0
    const board = { grid_size: n, tiles };
    return {
      board,
      solution,
      fingerprint: this.rngService.fingerprint(board),
      meta: { grid_size: n },
    };
  }

  /** Count inversions and fix parity so the puzzle is always solvable. */
  private ensureSolvable(tiles: number[], n: number): void {
    const blankIndex = tiles.indexOf(0);
    const flat = tiles.filter((t) => t !== 0);
    let inversions = 0;
    for (let i = 0; i < flat.length; i++) {
      for (let j = i + 1; j < flat.length; j++) {
        if (flat[i] > flat[j]) inversions++;
      }
    }
    let solvable: boolean;
    if (n % 2 === 1) {
      solvable = inversions % 2 === 0;
    } else {
      const blankRowFromBottom = n - Math.floor(blankIndex / n);
      solvable = (inversions + blankRowFromBottom) % 2 === 0;
    }
    if (!solvable) {
      // Swap the first two non-blank tiles to flip inversion parity.
      const a = tiles.findIndex((t) => t !== 0);
      const b = tiles.findIndex((t, idx) => t !== 0 && idx > a);
      [tiles[a], tiles[b]] = [tiles[b], tiles[a]];
    }
  }

  /** Validate that a submitted tile arrangement equals the solved state. */
  validateSlidingSolution(solution: number[], submitted: number[]): boolean {
    if (!Array.isArray(submitted) || submitted.length !== solution.length) return false;
    return solution.every((v, i) => v === submitted[i]);
  }

  // ─── MAZE (single optimal path, recursive backtracker) ─────────

  /**
   * Perfect maze via recursive backtracking. A perfect maze has exactly one path
   * between any two cells, so the entry→exit route is the unique shortest path.
   * BFS computes that shortest length for scoring.
   */
  private generateMaze(rng: DeterministicRng, config: any): GeneratedPuzzle {
    const n = this.clamp(Number(config?.grid_size ?? 10), 5, 30);
    // walls[r][c] = {N,E,S,W} booleans; true means wall present.
    const cells: Array<Array<{ N: boolean; E: boolean; S: boolean; W: boolean; v: boolean }>> = [];
    for (let r = 0; r < n; r++) {
      cells.push(
        Array.from({ length: n }, () => ({ N: true, E: true, S: true, W: true, v: false })),
      );
    }
    const stack: Array<[number, number]> = [[0, 0]];
    cells[0][0].v = true;
    const dirs: Array<['N' | 'E' | 'S' | 'W', number, number, 'N' | 'E' | 'S' | 'W']> = [
      ['N', -1, 0, 'S'],
      ['E', 0, 1, 'W'],
      ['S', 1, 0, 'N'],
      ['W', 0, -1, 'E'],
    ];
    while (stack.length) {
      const [r, c] = stack[stack.length - 1];
      const options = dirs.filter(([, dr, dc]) => {
        const nr = r + dr;
        const nc = c + dc;
        return nr >= 0 && nr < n && nc >= 0 && nc < n && !cells[nr][nc].v;
      });
      if (!options.length) {
        stack.pop();
        continue;
      }
      const [dir, dr, dc, opp] = rng.pick(options);
      const nr = r + dr;
      const nc = c + dc;
      cells[r][c][dir] = false;
      cells[nr][nc][opp] = false;
      cells[nr][nc].v = true;
      stack.push([nr, nc]);
    }
    const walls = cells.map((row) => row.map(({ N, E, S, W }) => ({ N, E, S, W })));
    const shortest = this.mazeShortestPath(walls, n);
    const board = { grid_size: n, walls, entry: [0, 0], exit: [n - 1, n - 1] };
    return {
      board,
      solution: { shortest },
      fingerprint: this.rngService.fingerprint(board),
      meta: { grid_size: n, shortest_path: shortest },
    };
  }

  /** BFS shortest path length (in cells) from entry to exit through open walls. */
  private mazeShortestPath(
    walls: Array<Array<{ N: boolean; E: boolean; S: boolean; W: boolean }>>,
    n: number,
  ): number {
    const dist = Array.from({ length: n }, () => new Array<number>(n).fill(-1));
    const queue: Array<[number, number]> = [[0, 0]];
    dist[0][0] = 1;
    const moves: Array<['N' | 'E' | 'S' | 'W', number, number]> = [
      ['N', -1, 0],
      ['E', 0, 1],
      ['S', 1, 0],
      ['W', 0, -1],
    ];
    while (queue.length) {
      const [r, c] = queue.shift()!;
      if (r === n - 1 && c === n - 1) return dist[r][c];
      for (const [dir, dr, dc] of moves) {
        if (walls[r][c][dir]) continue;
        const nr = r + dr;
        const nc = c + dc;
        if (nr < 0 || nr >= n || nc < 0 || nc >= n || dist[nr][nc] !== -1) continue;
        dist[nr][nc] = dist[r][c] + 1;
        queue.push([nr, nc]);
      }
    }
    return dist[n - 1][n - 1];
  }

  // ─── BLOCK FILL (Flow-style endpoints with guaranteed solution) ─

  /**
   * Generate a Hamiltonian-style single-path Block Fill board. We carve a single
   * snaking path that covers the grid, then expose its two endpoints as the dots
   * the player must connect — guaranteeing at least one valid full-coverage path.
   */
  private generateBlockFill(rng: DeterministicRng, config: any): GeneratedPuzzle {
    const n = this.clamp(Number(config?.grid_size ?? 5), 4, 9);
    // Boustrophedon (snake) Hamiltonian path guarantees full coverage.
    const path: Array<[number, number]> = [];
    for (let r = 0; r < n; r++) {
      if (r % 2 === 0) {
        for (let c = 0; c < n; c++) path.push([r, c]);
      } else {
        for (let c = n - 1; c >= 0; c--) path.push([r, c]);
      }
    }
    // Randomise which corner is start to vary the board deterministically.
    if (rng.next() < 0.5) path.reverse();
    const start = path[0];
    const end = path[path.length - 1];
    const board = { grid_size: n, endpoints: [start, end] };
    return {
      board,
      solution: { path },
      fingerprint: this.rngService.fingerprint(board),
      meta: { grid_size: n, path_length: path.length },
    };
  }

  /**
   * Validate a submitted Block Fill path covers every cell exactly once and
   * runs between the two endpoints with only orthogonal steps.
   */
  validateBlockFillSolution(n: number, endpoints: number[][], submitted: number[][]): boolean {
    if (!Array.isArray(submitted) || submitted.length !== n * n) return false;
    const seen = new Set<string>();
    for (const [r, c] of submitted) {
      if (r < 0 || r >= n || c < 0 || c >= n) return false;
      const key = `${r},${c}`;
      if (seen.has(key)) return false;
      seen.add(key);
    }
    // Endpoints must be the path ends (either orientation).
    const first = submitted[0];
    const last = submitted[submitted.length - 1];
    const matchEnds =
      (this.eq(first, endpoints[0]) && this.eq(last, endpoints[1])) ||
      (this.eq(first, endpoints[1]) && this.eq(last, endpoints[0]));
    if (!matchEnds) return false;
    // Every consecutive step must be orthogonally adjacent.
    for (let i = 1; i < submitted.length; i++) {
      const d = Math.abs(submitted[i][0] - submitted[i - 1][0]) + Math.abs(submitted[i][1] - submitted[i - 1][1]);
      if (d !== 1) return false;
    }
    return true;
  }

  // ─── HELPERS ───────────────────────────────────────────────────

  private eq(a: number[], b: number[]): boolean {
    return a[0] === b[0] && a[1] === b[1];
  }

  private clamp(v: number, min: number, max: number): number {
    if (Number.isNaN(v)) return min;
    return Math.max(min, Math.min(max, Math.round(v)));
  }
}
