/**
 * Application Constants
 */

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const REQUEST_CONTEXT = {
  USER: "user",
} as const;

export const TOKEN_TYPES = {
  LOGIN: 1,
  GAME_SESSION: 2,
} as const;

export const USER_TYPES = {
  USER: 1,
  ADMIN: 2,
} as const;

export const ERROR_CODES = {
  NO_SESSION: "NO_SESSION",
  NO_NEXT_LEVEL: "NO_NEXT_LEVEL",
  GAME_SESSION_NOT_ACTIVE: "GAME_SESSION_NOT_ACTIVE",
  GAME_SESSION_RECOVERY_REQUIRED: "GAME_SESSION_RECOVERY_REQUIRED",
  STAGE_ALREADY_PLAYED: "STAGE_ALREADY_PLAYED",
  FILE_REQUIRED: "FILE_REQUIRED",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  INVALID_IMAGE_FILE: "INVALID_IMAGE_FILE",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
  DIFFICULTY_NOT_FOUND: "DIFFICULTY_NOT_FOUND",
  SOME_DIFFICULTIES_NOT_FOUND: "SOME_DIFFICULTIES_NOT_FOUND",
  DIFFICULTY_NAME_TAKEN: "DIFFICULTY_NAME_TAKEN",
  LEVEL_NOT_FOUND: "LEVEL_NOT_FOUND",
  SOME_LEVELS_NOT_FOUND: "SOME_LEVELS_NOT_FOUND",
  LEVEL_NAME_TAKEN: "LEVEL_NAME_TAKEN",
  STAGE_CONFIG_NOT_FOUND: "STAGE_CONFIG_NOT_FOUND",
  SOME_STAGE_CONFIGS_NOT_FOUND: "SOME_STAGE_CONFIGS_NOT_FOUND",
  STAGE_CONFIG_POOL_TOO_SMALL: "STAGE_CONFIG_POOL_TOO_SMALL",
  ACTIVE_STAGE_CONFIG_NOT_FOUND: "ACTIVE_STAGE_CONFIG_NOT_FOUND",
  LEVEL_CONTENT_INVALID: "LEVEL_CONTENT_INVALID",
  REFERENCED_FILE_NOT_FOUND: "REFERENCED_FILE_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_ACCESS_DENIED: "SESSION_ACCESS_DENIED",
  INVALID_LEVEL_TRANSITION: "INVALID_LEVEL_TRANSITION",
  INVALID_MATCHED_PAIR_SUBMISSION: "INVALID_MATCHED_PAIR_SUBMISSION",
  PROGRESS_REGRESSION_NOT_ALLOWED: "PROGRESS_REGRESSION_NOT_ALLOWED",
  LEVEL_NOT_COMPLETED: "LEVEL_NOT_COMPLETED",
  INVALID_CARD_SUBMISSION: "INVALID_CARD_SUBMISSION",
  FLIP_TIMESTAMP_IN_FUTURE: "FLIP_TIMESTAMP_IN_FUTURE",
  FLIP_BLOCKED_BY_MISMATCH: "FLIP_BLOCKED_BY_MISMATCH",
  LEVEL_NOT_READY_TO_END: "LEVEL_NOT_READY_TO_END",
} as const;

export const GAME_SESSION_STATUS = {
  STARTED: "STARTED",
  RESULT_PROCESSING: "RESULT_PROCESSING",
} as const;

export const GAME_CONFIGS = {
  EXPIRY_GRACE_SECONDS: 5,
  ACTION_TIMESTAMP_FUTURE_SKEW_MS: 10_000,
  SQS_POLL_ERROR_RETRY_MS: 5_000,
} as const;

export const ANTI_CHEAT_CONFIGS = {
  CLICK_TOO_FAST_MS: 50,
  UNIFORM_TIMING_CV_THRESHOLD: 0.1,
  UNIFORM_TIMING_MIN_INTERVALS: 3,
  IMPOSSIBLE_SOLVE_MS_PER_PAIR: 1_000,
} as const;

export const CHEAT_FLAG_TYPE = {
  CLICK_TOO_FAST: 1,
  UNIFORM_TIMING: 2,
  REMAINING_PAIRS_AT_END: 3,
  IMPOSSIBLE_SOLVE_TIME: 4,
} as const;

export const CRYPTO_CONFIGS = {
  ALGORITHM: "aes-256-gcm",
  IV_LENGTH_BYTES: 12,
  KEY_LENGTH_BYTES: 32,
} as const;

export const IMAGE_COMPRESSION_CONFIG = {
  JPEG_QUALITY: 75,
  WEBP_QUALITY: 75,
  PNG_COMPRESSION_LEVEL: 9,
} as const;

export const IMAGE_MIME_TYPES = {
  JPEG: "image/jpeg",
  PNG: "image/png",
  WEBP: "image/webp",
} as const;

export const RESTATE_SERVICES = {
  GAME_SESSION: "MemoryCardGameSession",
  GAME_EXPIRY: "MemoryCardGameExpiry",
} as const;

export const DEFAULT_STAGE_ID = "default";

export const DEFAULT_STAGE_CONFIG = {
  TIME_LIMIT: 60,
  BOARD_COUNT: 1,
  DEMO_BOARD_COUNT: 1,
  ENABLE_DEMO: false,
} as const;

export const GAME_CONFIG_EVENT_TYPE = {
  STAGE_ATTACHED: "GAME_STAGE_ATTACHED",
  STAGE_DETACHED: "GAME_STAGE_DETACHED",
} as const;

/** Maximum value for a PostgreSQL INTEGER (INT4) column. */
export const INT4_MAX = 2147483647;

export type TokenType = (typeof TOKEN_TYPES)[keyof typeof TOKEN_TYPES];
export type UserType = (typeof USER_TYPES)[keyof typeof USER_TYPES];
export type CheatFlagType =
  (typeof CHEAT_FLAG_TYPE)[keyof typeof CHEAT_FLAG_TYPE];
