export enum GameConfigEventType {
    CREATED = 'GAME_CREATED',
    UPDATED = 'GAME_UPDATED',
    DELETED = 'GAME_DELETED',
    STAGE_ATTACHED = 'GAME_STAGE_ATTACHED',
    STAGE_DETACHED = 'GAME_STAGE_DETACHED',
}
