ALTER TABLE "cheat_flags"
ALTER COLUMN "flag_type" TYPE INTEGER
USING CASE "flag_type"
    WHEN 'CLICK_TOO_FAST' THEN 1
    WHEN 'UNIFORM_TIMING' THEN 2
    WHEN 'REMAINING_PAIRS_AT_END' THEN 3
    WHEN 'IMPOSSIBLE_SOLVE_TIME' THEN 4
    ELSE NULL
END;
