export const BOARD_SOLVED_TRANSITION_MS = 420;
export const SOLVED_NEXT_BOARD_HOLD_MS = 600;
export const SOLVED_RESULT_REVEAL_DELAY_MS = 1000;
export const FINAL_DEMO_REDIRECT_DELAY_MS = 900;
export const ROTATE_BATCH_ACK_TIMEOUT_MS = 500;
export const PENDING_ROTATION_STALE_MS = 5000;
export const PENDING_ROTATION_CHECK_INTERVAL_MS = 1000;
export const TUTORIAL_LEVEL_COUNT = 2;
