export {
  createGameBoard,
  createInfinityLevel,
  createMazeTemplate,
  createSlidingPuzzleBoard,
  createSlidingPuzzleLevel,
  deleteGameBoards,
  deleteInfinityLevels,
  deleteMazeTemplate,
  deleteMazeTemplatesSequentially,
  deleteSlidingPuzzleBoards,
  deleteSlidingPuzzleLevels,
  fetchBoardDetails,
  fetchBoardDetailsByPath,
  fetchDifficulties,
  fetchGameBoards,
  fetchInfinityLevels,
  fetchLevels,
  fetchMazeTemplateDetails,
  fetchMazeTemplates,
  fetchSlidingPuzzleBoardDetails,
  fetchSlidingPuzzleBoards,
  fetchSlidingPuzzleLevels,
  generateMazeTemplate,
  updateGameBoard,
  updateSlidingPuzzleBoard,
  updateSlidingPuzzleLevel,
} from "@/lib/api/endpoints/pools";
